# Source: demo-go-app/templates/demo-app.yaml
kind: Service
apiVersion: v1
metadata:
  name: demo-app-lb-prod
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: demo-app
    role: frontend
    env: prod
    color: blue
---
# Source: demo-go-app/templates/demo-app.yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-app-prod
spec:
  replicas: 4
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        role: frontend
        env: prod
        color: green
    spec:
      containers:
      - name: frontend
        image: harshals/demo-go-app:master.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
        ports:
        - name: frontend
          containerPort: 8000
---
# Source: demo-go-app/templates/demo-app.yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-app-canary
spec:
  replicas: 4
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        role: frontend
        # env: canary
        color: blue
    spec:
      containers:
      - name: frontend
        image: harshals/demo-go-app:canary.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
        ports:
        - name: frontend
          containerPort: 8000
